runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/angular-frontend/index.html
  upload: dist/angular-frontend/index.html

- url: /
  static_dir: dist/angular-frontend